### ISSUE TITLE
Crashed SMAC in combination with default validation

### ISSUE THREAD

**Issue by mlindauer** [sfalkner/SpySMAC#3]
I get a new error:

``` bash
15:14:48.114 [main] ERROR c.u.c.b.smac.executors.SMACExecutor - Message: File: /pfs/work3/workspace/scratch/fr_tl1023-spysmac-exp-0/gcthreads/./out/scenario/state-run1/java_obj_dump-v2-it0.obj already exists
15:14:48.114 [main] ERROR c.u.c.b.smac.executors.SMACExecutor - Exception:java.lang.IllegalStateException
15:14:48.115 [main] ERROR c.u.c.b.smac.executors.SMACExecutor - StackTrace:java.lang.IllegalStateException: File: /pfs/work3/workspace/scratch/fr_tl1023-spysmac-exp-0/gcthreads/./out/scenario/state-run1/java_obj_dump-v2-it0.obj already exists
        at ca.ubc.cs.beta.aeatk.state.legacy.LegacyStateSerializer.save(LegacyStateSerializer.java:215)
        at ca.ubc.cs.beta.smac.configurator.AbstractAlgorithmFramework.saveState(AbstractAlgorithmFramework.java:431)
        at ca.ubc.cs.beta.smac.configurator.AbstractAlgorithmFramework.saveState(AbstractAlgorithmFramework.java:395)
        at ca.ubc.cs.beta.smac.configurator.AbstractAlgorithmFramework.run(AbstractAlgorithmFramework.java:539)
        at ca.ubc.cs.beta.smac.executors.SMACExecutor.oldMain(SMACExecutor.java:140)
        at ca.ubc.cs.beta.smac.executors.SMACExecutor.main(SMACExecutor.java:104)
```

The error only popped up after I ran simultaneously the validation of the default.
It's also reproducible that it is only the first SMAC  run (seed 1) that throws this error.
Therefore, I assume we have a race-condition between the "real" SMAC runs and the validation run of the default configuration.

Best,
Marius

**Comment by sfalkner** [comment]
Hmmm... Could you run the validation run on its own and see how many state-run folder it creates. I don't see how "/out/scenario/state-run1/java_obj_dump-v2-it0.obj" is created by the validation run. Unless you run it with more than one run, and I messed up the limitation that when the seed=0 it should ignore the num-runs and num-procs arguments.

Best,

Stefan

**Comment by mlindauer** [comment]
I'm very sorry; it's my mistake. I run indeed --seed 1 instead of --seed 0

**Comment by sfalkner** [comment]
My favorite issues are the ones that resolve themselves :)
